@startuml packages_pydantify
set namespaceSeparator none
package "pydantify" as pydantify #aliceblue {
}
package "pydantify.__main__" as pydantify.__main__ #aliceblue {
}
package "pydantify.exceptions" as pydantify.exceptions #aliceblue {
}
package "pydantify.main" as pydantify.main #aliceblue {
}
package "pydantify.models" as pydantify.models #antiquewhite {
}
package "pydantify.models.base" as pydantify.models.base #antiquewhite {
}
package "pydantify.models.models" as pydantify.models.models #antiquewhite {
}
package "pydantify.models.nodefactory" as pydantify.models.nodefactory #antiquewhite {
}
package "pydantify.models.typeresolver" as pydantify.models.typeresolver #antiquewhite {
}
package "pydantify.plugins" as pydantify.plugins #aquamarine {
}
package "pydantify.plugins.pydantic_plugin" as pydantify.plugins.pydantic_plugin #aquamarine {
}
package "pydantify.run" as pydantify.run #aliceblue {
}
package "pydantify.utility" as pydantify.utility #burlywood {
}
package "pydantify.utility.function_tools" as pydantify.utility.function_tools #burlywood {
}
package "pydantify.utility.model_generator" as pydantify.utility.model_generator #burlywood {
}
package "pydantify.utility.patterns" as pydantify.utility.patterns #burlywood {
}
package "pydantify.utility.restconf" as pydantify.utility.restconf #burlywood {
}
package "pydantify.utility.yang_sources_tracker" as pydantify.utility.yang_sources_tracker #burlywood {
}
pydantify.__main__ --> pydantify.main
pydantify.main --> pydantify.run
pydantify.main --> pydantify.utility.model_generator
pydantify.models --> pydantify.models.base
pydantify.models --> pydantify.models.models
pydantify.models --> pydantify.models.nodefactory
pydantify.models --> pydantify.models.typeresolver
pydantify.models.base --> pydantify.models.nodefactory
pydantify.models.models --> pydantify.exceptions
pydantify.models.nodefactory --> pydantify.exceptions
pydantify.plugins.pydantic_plugin --> pydantify.utility.model_generator
pydantify.utility --> pydantify.utility.function_tools
pydantify.utility --> pydantify.utility.restconf
pydantify.utility --> pydantify.utility.yang_sources_tracker
@enduml
